### PR TITLE
Add github action

### PR DESCRIPTION
**Pull request by bensuperpc**
Add github action:
- Add build with ubuntu 18.04 and 20.04
- Add build with GCC and Clang
- Add dependabot
- Add stalebot

### CODE REVIEW

**Comment by Fantu** [comment]
good addition
about the build I suggest build also on newer system (ubuntu 18.04 and 20.04 are now quite "old"), for example debian unstable to check if build also on latest version of gcc (or others)

**Comment by bensuperpc** [comment]
> good addition about the build I suggest build also on newer system (ubuntu 18.04 and 20.04 are now quite "old"), for example debian unstable to check if build also on latest version of gcc (or others)

This is still in [beta](https://github.com/actions/virtual-environments/issues/5490), i added ubuntu 22.04 ^^

**Comment by debrouxl** [comment]
I'm no Github action expert, but this looks reasonable :)

**Comment by x86fr** [comment]
Let's try it!

**Comment by x86fr** [comment]
Add github action:
- Add build with ubuntu 18.04 and 20.04
- Add build with GCC and Clang
- Add dependabot
- Add stalebot

**Pull request merged**
