### PR TITLE
Sequential SPD read optimization for DDR4 and DDR5

### PR DESCRIPTION
**Pull request by TommiTheFirst**
The code I have created here tries too leverage the internal address counter of the SPD, which is incremented each time a byte is read.

### CODE REVIEW

**Comment by x86fr** [comment]
What's the ultimate goal here?

**Comment by TommiTheFirst** [comment]
> What's the ultimate goal here?

It's just a small optimization, nothing more significant than that.

The goal is too avoid Random address reads (perform a dummy write to load the address into the address counter before reading from the address) by forcing Sequential reads (read directly from the next byte in the sequence).

The way we achieved is with the help of the `volatile` keyword too force `get_spd` to be called in a sequential way. Ensuring the codes ability to leverage this EEPROM reading optimization.

I am not sure how common this is on most SPD controllers, but from the ones I've read about it seems to be a thing.

The reason i made this DDR4 and DDR5 only is because those are the only DDR gens i currently can test with, and the only ones I've actively read anything about.

**Comment by martinwhitaker** [comment]
I don't see the point of optimising code that is only executed once at program startup and doesn't cause a noticeable delay, and I don't know if the hardware is smart enough to benefit from changing the read order, .but in any case `|` is not a short-circuiting operator, so you have no guarantee the compiler will choose to execute the calls to `get_spd()` in the order they are written.

**Comment by debrouxl** [comment]
I'm for taking advantage of hardware capabilities, when available (*). However, optimizing this code for size makes more sense than optimizing it for speed... and for that, switching to fixed-point ( #429 ) - if it can be made to work accurately - is a more efficient way.
Therefore... while I don't think that your approach is worthless, I don't think that there's a real incentive to merge it under that form, either :)

*: a block mode for reading 128 or 256 bytes at a time, akin to write block mode for some Flash memory models, would be so much more efficient than many calls for reading individual bytes...

**Comment by debrouxl** [comment]
BTW, about size optimization:
```
diff --git a/system/spd.c b/system/spd.c
index f0f7630..86eb844 100644
--- a/system/spd.c
+++ b/system/spd.c
@@ -195,7 +195,7 @@ static void parse_spd_ddr5(spd_info *spdi, uint8_t slot_idx)
 
     // Compute Frequency (including XMP)
     uint16_t tCK, tCKtmp, tns;
-    int xmp_offset = 0;
+    uint16_t xmp_offset = 0;
 
     spdi->XMP = ((get_spd(slot_idx, 640) == 0x0C && get_spd(slot_idx, 641) == 0x4A)) ? 3 : 0;
 
@@ -226,66 +226,37 @@ static void parse_spd_ddr5(spd_info *spdi, uint8_t slot_idx)
 
     // Module Timings
     if (spdi->XMP == 3) {
-        // ------------------
-        // XMP Specifications
-        // ------------------
-
-        // CAS# Latency
-        tns  = (uint16_t)get_spd(slot_idx, 718 + xmp_offset) << 8 |
-               (uint16_t)get_spd(slot_idx, 717 + xmp_offset);
-        spdi->tCL = (tns + tCK - DDR5_ROUNDING_FACTOR) / tCK;
-        spdi->tCL += spdi->tCL % 2; // if tCL is odd, round to upper even.
-
-        // RAS# to CAS# Latency
-        tns  = (uint16_t)get_spd(slot_idx, 720 + xmp_offset) << 8 |
-               (uint16_t)get_spd(slot_idx, 719 + xmp_offset);
-        spdi->tRCD = (tns + tCK - DDR5_ROUNDING_FACTOR) / tCK;
-
-        // RAS# Precharge
-        tns  = (uint16_t)get_spd(slot_idx, 722 + xmp_offset) << 8 |
-               (uint16_t)get_spd(slot_idx, 721 + xmp_offset);
-        spdi->tRP = (tns + tCK - DDR5_ROUNDING_FACTOR) / tCK;
-
-        // Row Active Time
-        tns  = (uint16_t)get_spd(slot_idx, 724 + xmp_offset) << 8 |
-               (uint16_t)get_spd(slot_idx, 723 + xmp_offset);
-        spdi->tRAS = (tns + tCK - DDR5_ROUNDING_FACTOR) / tCK;
-
-        // Row Cycle Time
-        tns  = (uint16_t)get_spd(slot_idx, 726 + xmp_offset) << 8 |
-               (uint16_t)get_spd(slot_idx, 725 + xmp_offset);
-        spdi->tRC = (tns + tCK - DDR5_ROUNDING_FACTOR) / tCK;
-    } else {
-        // --------------------
-        // JEDEC Specifications
-        // --------------------
-
-        // CAS# Latency
-        tns  = (uint16_t)get_spd(slot_idx, 31) << 8 |
-               (uint16_t)get_spd(slot_idx, 30);
-        spdi->tCL = (tns + tCK - DDR5_ROUNDING_FACTOR) / tCK;
-        spdi->tCL += spdi->tCL % 2;
-
-        // RAS# to CAS# Latency
-        tns  = (uint16_t)get_spd(slot_idx, 33) << 8 |
-               (uint16_t)get_spd(slot_idx, 32);
-        spdi->tRCD = (tns + tCK - DDR5_ROUNDING_FACTOR) / tCK;
-
-        // RAS# Precharge
-        tns  = (uint16_t)get_spd(slot_idx, 35) << 8 |
-               (uint16_t)get_spd(slot_idx, 34);
-        spdi->tRP = (tns + tCK - DDR5_ROUNDING_FACTOR) / tCK;
-
-        // Row Active Time
-        tns  = (uint16_t)get_spd(slot_idx, 37) << 8 |
-               (uint16_t)get_spd(slot_idx, 36);
-        spdi->tRAS = (tns + tCK - DDR5_ROUNDING_FACTOR) / tCK;
-
-        // Row Cycle Time
-        tns  = (uint16_t)get_spd(slot_idx, 39) << 8 |
-               (uint16_t)get_spd(slot_idx, 38);
-        spdi->tRC = (tns + tCK - DDR5_ROUNDING_FACTOR) / tCK;
-    }
+        xmp_offset += 718 - 31;
+    }
+    // --------------------------
+    // JEDEC / XMP Specifications
+    // --------------------------
+
+    // CAS# Latency
+    tns  = (uint16_t)get_spd(slot_idx, 31 + xmp_offset) << 8 |
+           (uint16_t)get_spd(slot_idx, 30 + xmp_offset);
+    spdi->tCL = (tns + tCK - DDR5_ROUNDING_FACTOR) / tCK;
+    spdi->tCL += spdi->tCL % 2; // if tCL is odd, round to upper even.
+
+    // RAS# to CAS# Latency
+    tns  = (uint16_t)get_spd(slot_idx, 33 + xmp_offset) << 8 |
+           (uint16_t)get_spd(slot_idx, 32 + xmp_offset);
+    spdi->tRCD = (tns + tCK - DDR5_ROUNDING_FACTOR) / tCK;
+
+    // RAS# Precharge
+    tns  = (uint16_t)get_spd(slot_idx, 35 + xmp_offset) << 8 |
+           (uint16_t)get_spd(slot_idx, 34 + xmp_offset);
+    spdi->tRP = (tns + tCK - DDR5_ROUNDING_FACTOR) / tCK;
+
+    // Row Active Time
+    tns  = (uint16_t)get_spd(slot_idx, 37 + xmp_offset) << 8 |
+           (uint16_t)get_spd(slot_idx, 36 + xmp_offset);
+    spdi->tRAS = (tns + tCK - DDR5_ROUNDING_FACTOR) / tCK;
+
+    // Row Cycle Time
+    tns  = (uint16_t)get_spd(slot_idx, 39 + xmp_offset) << 8 |
+           (uint16_t)get_spd(slot_idx, 38 + xmp_offset);
+    spdi->tRC = (tns + tCK - DDR5_ROUNDING_FACTOR) / tCK;
 
     // Module manufacturer
     spdi->jedec_code = (get_spd(slot_idx, 512) & 0x1F) << 8;
```
saves nearly 300 bytes, with further gains to come for AMD EXPO support, unless AMD did fancy changing the offset layout (I can't find the specification online easily).

**Pull request closed without merging**
